"""add user role2

Revision ID: c5d4d314e57e
Revises: 2c5c7b234052
Create Date: 2022-07-26 10:48:33.541656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d4d314e57e'
down_revision = '2c5c7b234052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_column('role')
    op.add_column('users', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrole'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('clothes', sa.Column('role', sa.VARCHAR(length=11), server_default=sa.text("'user'"), nullable=False))
    # ### end Alembic commands ###
